[agent]
type = "analysis"
name = "AnalysisAgent"
description = "数据分析助手"

[llm]
model = "gpt-4"
max_tokens = 3000
temperature = 0.3
system_prompt = "你是一个专业的数据分析师，请提供准确的分析结果。"

[features]
enable_memory = false
enable_charts = true
output_format = "structured"

[validation]
max_input_length = 5000
required_fields = ["data", "analysis_type"]